### ISSUE TITLE
Usage question: shifting bits from a slice into a register

### ISSUE THREAD

**Issue by cole-miller** [bitvecto-rs/bitvec#108]
Hi! I have some bit-twiddling to do and I'm trying to figure out how to express it with bitvec. (I hope it's okay to post usage questions in this tracker.) The setup: I have a `u16` "register" and a `BitSlice`. Given `n: usize`, I want to shift `n` bits out of the beginning of the slice and into the register from below (i.e. so that the least-significant bit is filled first); if the slice has fewer than `n` bits I want the remaining bits to be all `1`s. So:

before: `register = 0b00000000_00000000`, `slice = [1, 0, 1, 1]`, `n = 6`
after: `register = 0b00000000_00101111`, `slice = []`

Thanks very much for your work on this crate -- it's an impressive project!

**Comment by myrrlyn** [comment]
You can do this with

```rust
let mut reg = 0u16;

for bit in bit_slice.iter().by_val().chain(iter::repeat(true)).take(n) {
  reg <<= 1;
  reg |= bit as u16
}
```

or

```rust
let mut reg = 0u16;
let reg_bits = reg.view_bits_mut::<Lsb0>();

let lsedge_ones = n - bits.len();
reg_bits[.. lsedge_ones].set_all(true);
reg_bits[lsedge_ones .. n].store(
  bits.load::<u16>()
);
```

Note that the second snippet will require careful checking to make sure that the [`BitField`](https://docs.rs/bitvec/latest/bitvec/field/trait.BitField.html) functionality is producing the bit patterns you expect. On `u16`s it can be surprising! If you can't get it to do exactly what you want, then you can just iterate across each and copy bits from one to the other.

**Comment by cole-miller** [comment]
Much appreciated!
