### ISSUE TITLE
bitvec 0.21 should depend on funty 1.2

### ISSUE THREAD

**Issue by mbrubeck** [bitvecto-rs/bitvec#112]
bitvec 0.21 will only build with funty 1.2.0 or later, but it still specifies `funty = "1"` in its dependencies.  This can cause broken builds if existing project update bitvec without also updating funty.

**Comment by mbrubeck** [comment]
(I would submit a patch for this, but I can't find the source code corresponding to bitvec 0.21.0 on GitHub.)

**Comment by tmplt** [comment]
Explains why my crate decided to simply not build anymore just now. Adding `funty = "=1.2.0"` fixes it.

I've never stumbled upon an issue like this before. Why does me adding `funty` to my crate's scope affect the scope of `bitvec`? Aren't crates built in isolation?

**Comment by mbrubeck** [comment]
> Explains why my crate decided to simply not build anymore just now. Adding `funty = "=1.2.0"` fixes it.

Instead of editing your `Cargo.toml`, you can just run `cargo update -p funty`, which will update your `Cargo.lock` file to use the latest version.

> Why does me adding `funty` to my crate's scope affect the scope of `bitvec`?

If two crates depend on `funty`, then Cargo will attempt to find a single version of `funty` that satisfies both of them.  For example, if `bitvec` requires `funty = "1"` and your crate requires `funty = "1.2"`, then Cargo can select version 1.2.0 which meets both requirements.

**Comment by mbrubeck** [comment]
It looks like this is fixed in bitvec 0.21.1.
