### ISSUE TITLE
The BitSlice example "trim" doesn't work for empty result slices

### ISSUE THREAD

**Issue by KarelPeeters** [bitvecto-rs/bitvec#113]
Hey! I'm a new user to this crate, and while reading through the docs I noticed that the first example [here](https://docs.rs/bitvec/0.21.1/bitvec/slice/struct.BitSlice.html) seems to have a bad edge case when the returned slice _should_ be empty. This can occur if the imput slice was empty or all `to_trim`. For the empty input the function craches and for the other case a wrong range still containing a value that should be trimmed is returned.

I think the easiest fix is replacing the last two lines of the function body by this:

```rust
let back = bits.iter().by_ref().rposition(stop).map_or(0, |p| p + 1);
&bits[front..back]
```

This is not a very big deal but it's always nice when the examples actually work 🙂.

**Comment by myrrlyn** [comment]
*Embarassing*. Your issue was immediately followed by #114, which is *also* about my difficult relationship with off-by-one errors when walking a slice backwards.

You are correct; thank you for the report.
