### ISSUE TITLE
Allow to take empty ranges at the end of a bitvector

### ISSUE THREAD

**Issue by sebschmi** [bitvecto-rs/bitvec#118]
The following code compiles and runs without error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=05e1a44fc688cccc1e417bb7d2e779bc)):

```rust
fn main() {
    let v = vec![0, 1, 2];
    let slice = &v[3..3];
    println!("slice {:?}", slice);
}
```

However, [this line](https://github.com/bitvecto-rs/bitvec/blob/d00b25cce6f7a390ed5a3b7eff68e4ef7eb00df9/src/slice/api.rs#L2638) in this crate disallows the equivalent to work for bitvectors. That is, the following code does compile, but panics:

```rust
use bitvec::prelude::*;

fn main() {
    let bitvec = bitvec![0, 1, 2];
    let bitslice = &bitvec[3..3];
    println!("bitslice {:?}", bitslice);
}
```

Is there a specific reason, for why it is impossible to take an empty slice at the end of the bitvector?

It would be particularly useful to create custom iterators for bitvector-like types, since it can then just contain a slice and the next function would update the slice as follows:

```rust
// inside the next function of the Iterator trait implementation
self.bitslice = &self.bitslice[1..];
```

**Comment by myrrlyn** [comment]
*Any* observable behavior difference from the standard library is a failure on my part. I try to literally transcribe source code where possible but it's tedious enough to do that I am not always proäctive about it.

**Comment by myrrlyn** [comment]
I will issue patch releases to the minor series after I go through my other issues today. Thank you for the report!

**Comment by sebschmi** [comment]
Thank you very much for the fast fix, and thanks for making this amazing crate!
