### ISSUE TITLE
Backport #114 fix to 0.20.x series

### ISSUE THREAD

**Issue by hzuo** [bitvecto-rs/bitvec#122]
The changelog says that the fix for #114 has been backported to the 0.20.x series, but this isn't yet the case.

My package currently needs to stay on the 0.20.x series due to the incompatible funty 1.2 release - it depends on crates who transitively depend on funty ~1.1, and Cargo does not let `~1.1` and `~1.2` coexist in the same dependency tree.

**Comment by myrrlyn** [comment]
I completely forgot to reach it! I'm so sorry. `0.20.3` is now live

**Comment by hzuo** [comment]
Thank you!
