### ISSUE TITLE
Is it possible to create version 19.6 of bitvec without the Tarpaulin configuration directive   

### ISSUE THREAD

**Issue by eyalsatori** [bitvecto-rs/bitvec#130]
Hi , 

Many people  that use the [nom](https://github.com/Geal/nom/) create currently can't run Tarpaulin , because nom require 0.19.X version of bitvec , and this version contains Tarpaulin cfg directive that not supported anymore  (for example see : https://github.com/xd009642/tarpaulin/issues/756). 

I think maybe it's possible to create new release 0.19.6 of bitvec , that rebased on 0.19.5 but just without those directives (they already removed in the current version of bitvec) , and make all nom user happy :) . 

If it's possible it's will be great !!!

**Comment by myrrlyn** [comment]
I apologize for the egregious delay. Thank you for pinging me about this earlier as well. I have [published v0.19.6](https://crates.io/crates/bitvec/0.19.6) with the final `#![cfg_attr(tarpaulin, skip)]` attribute removed.
