### ISSUE TITLE
[bug] leading_ones failed test

### ISSUE THREAD

**Issue by maks83** [bitvecto-rs/bitvec#152]
#[test]
    fn test_leading_ones() {
        use bitvec::prelude::*;
        const N: usize = 224;
        let mut map: BitArr!(for N, in LocalBits, u32) = BitArray::zeroed();
        for i in 0..N {
            map.set(i, true);
        }
        assert_eq!(map.leading_ones(), N); // actual value is 0
    }

with N = 223 or N = 225 test is ok.
bitvec version = "0.22.3"
os = maxOS Catalina

**Comment by myrrlyn** [comment]
This is the same error as reported in #127. I am currently focusing on releasing v1, and encourage my users to upgrade to it when able. If you are not, I am willing to release a fix on 0.22 once 1.0.0 is done.

Thank you for reporting it, though.

**Comment by myrrlyn** [comment]
Okay now that I have a tracker for it, I'm going to close this. *Please* do re-open or otherwise ping me if you prefer to stay on 0.22 instead of move to 1.0, though! Closure is just to track what I have left to do, not a dismissal.
