### ISSUE TITLE
Missing concrete return type for `Iter::by_vals`

### ISSUE THREAD

**Issue by dignifiedquire** [bitvecto-rs/bitvec#169]
I trying to upgrade from `0.22` to `1.0` and running into the following issue.
I have a trait like this

```rust
pub trait MyTrait {
  type Iter: Iterator<Item = bool>;
  fn iter(self) -> Self::Iter;
}
```

which currently is implemented using sth like this: 

```rust 
pub struct Foo {
  bv: BitVec,
}

impl<'a> MyTrait for &'a Foo {
  type Iter: bitvec::slice::BitValIter<'a, Lsb0, usize>;
  fn iter(self) -> Self::Iter {
    self.bv.iter().by_val()
  }
}
```

Unfortunately in `1.0` calling `.by_vals()` returns an opaque type (`impl Iterator<Item = bool>`) which I cannot use anymore in this trait definition. Any pointers on how to either work around this, or if this could be changed to return a concrete type again? Thank you

**Comment by dignifiedquire** [comment]
@myrrlyn any thoughts?

**Comment by myrrlyn** [comment]
You're right. I didn't think about that when I made the switch. Since this should be a patch-compatible change, it'll be in 1.0.2.

**Comment by dignifiedquire** [comment]
thank you!
