### ISSUE TITLE
Read panics when exact length of BitVec is read

### ISSUE THREAD

**Issue by dgkf** [bitvecto-rs/bitvec#170]
Reading into a `Vec<u8>` with a length that would exactly exhaust a `BitVec` throws a seemingly erroneous message.

```rust
use std::io::Read;
use bitvec::prelude::*;

let mut data: Vec<u8> = vec![0; 1];
bits![0; 8].to_bitvec().read(&mut data);
```
```
panicked at 'cannot shift a bit-slice by more than its length: 8 > 8'
/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/bitvec-1.0.0/src/slice.rs:1419:9
```

The communicated panic condition, `8 > 8` is not true, so it's unclear what needs to change to resolve this panic.

https://github.com/bitvecto-rs/bitvec/blob/a7a82c67206d6e3ced67294883f6d1baaae7d74c/src/slice.rs#L1419-L1424

I'm new to working with bitwise data and I'm not familiar with the inner workings of the crate, so the correct behavior isn't obvious to me. As it is now, there's at least a bit of a ambiguity when `by == len` as a result of a `read`.

**Comment by myrrlyn** [comment]
This is likely fixed by f035ce4c. It's an incorrect edge case in the implementations of `shift_{left,right}`. I will release a `v1.0.2` with this included in it soon.

Thank you for the report. I apologize for the delay in responding to it; I have been extremely busy offline.
