### ISSUE TITLE
Bitslice<u8, Msb0> chunk returns unexpected result for `load::<u8>()` in some cases

### ISSUE THREAD

**Issue by dblclik** [bitvecto-rs/bitvec#187]
Hello -- I just started using this crate, so in the event that this is a user-error, please do not hesitate to set me straight :)  So far it is very helpful, thank you for authoring it!

I am using v1.0.1 of bitvec, and I am working on a Base64 encoding library and noticed that when I do `bits.chunk(6)` (where `bits: &BitSlice<u8, Msb0>`) and one of the 6-bit chunks is `[0,0,0,1,1,0]`, the u8 conversion, done via `chunk.load::<u8>())`, results in `24` instead of `6`. 

I haven't gone through a search of bit slices and the result of loading them (though I will later this afternoon), and, unfortunately, I don't know if I understand the `load()` method well enough to say why this is happening only in this case (but would very much like to).

Here is a snippet of Rust code that should compile and show the difference from expected for each chunk (call `print_bits()` in `main.rs`)

```rust
use bitvec::prelude::*;

pub fn b2(bits: &bitvec::slice::BitSlice<u8, bitvec::order::Msb0>) -> u32 {
    let base: u32 = 2;
    let mut value = 0;
    let mut index: u32 = bits.len() as u32;
    let value = bits.iter().fold(0, |_, x| {
        index -= 1;
        if *x {
            value = value + base.pow(index);
        }
        value
    });
    value
}

pub fn print_bits() {
    let buffer = "hello".as_bytes().to_owned();
    // Consume original buffer in u8 to a BitVec buffer
    let bits = buffer.view_bits::<Msb0>();
    // println!("{:?}", bits);
    let bits_iter = bits.chunks(6);
    for chunk in bits_iter {
        println!("chunk is: {:?}", chunk);
        println!("chunk as u8 is: {:?}", chunk.load::<u8>());
        println!("chunk as u8 via b2 func is: {}", b2(chunk));
    }
}
```

The output I get is in the screenshot below:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/3995753/178159848-ab67b6f6-ac91-49e3-8e85-1563ef3ffea5.png">

**Comment by dblclik** [comment]
It definitely seems to be an issue with how I am initializing and chunking the first BitSlice because this check of all B64 values (i.e. u6) checks out just fine.  I am curious though why there is an issue in the code I included above as it seems to only happen when the chunk is `[0,0,0,1,1,0]`

```rust
pub fn search_bits() {
    let bit_arr: [Vec<u8>; 64] = [vec![0],vec![1],vec![2],vec![3],vec![4],
        vec![5],vec![6],vec![7],vec![8],vec![9],vec![10],vec![11],vec![12],
        vec![13],vec![14],vec![15],vec![16],vec![17],vec![18],vec![19],vec![20],
        vec![21],vec![22],vec![23],vec![24],vec![25],vec![26],vec![27],vec![28],
        vec![29],vec![30],vec![31],vec![32],vec![33],vec![34],vec![35],vec![36],
        vec![37],vec![38],vec![39],vec![40],vec![41],vec![42],vec![43],vec![44],
        vec![45],vec![46],vec![47],vec![48],vec![49],vec![50],vec![51],vec![52],
        vec![53],vec![54],vec![55],vec![56],vec![57],vec![58],vec![59],vec![60],
        vec![61],vec![62],vec![63]
    ];
    for bits in bit_arr {
        let bit = bits.view_bits::<Msb0>();
        let (_, bit6) = bit.split_at(2);
        println!("{:?}", bit6);
        println!("chunk as u8 is: {:?}", bit6.load::<u8>());
        println!("chunk as u8 via b2 func is: {}", b2(bit6));
    }
}
```

**Comment by dblclik** [comment]
This snippet below finds a lot more instances of the load not resulting in the expected value, but I don't see a pattern at first (thought maybe it had to do with what the preceding chunk might be, but does not appear so).

If it is alright, I would love to find out why this is happening, but feel free to mark the issue as `Closed` as long as we can still message about it.  Thank you!

```rust
pub fn print_bits() {
    let buffer = "hello this is a much longer test and I am curious about what causes this issue"
        .as_bytes()
        .to_owned();
    // Consume original buffer in u8 to a BitVec buffer
    let bits = buffer.view_bits::<Msb0>();
    // println!("{:?}", bits);
    let bits_iter = bits.chunks(6);
    let mut chunk_index = 0;
    for chunk in bits_iter {
        chunk_index += 1;
        let load_u8 = chunk.load::<u8>();
        let b2_u8 = b2(chunk) as u8;
        if load_u8 != b2_u8 {
            println!("chunk {chunk_index} is: {:?}", chunk);
            println!("chunk as u8 is: {:?}", load_u8);
            println!("chunk as u8 via b2 func is: {}", b2_u8);
        }
    }
}
```

**Comment by myrrlyn** [comment]
you probably want to use `.load_be()`. the `BitField` trait does not guarantee numeric equivalence with any other bit-setting operations; it can only guarantee that it will `.load()` out exactly what you `.store()`d in (w.r.t. integer truncations and signage)

the user guide has [a chapter](https://bitvecto-rs.github.io/bitvec/practical-use/bitfields.html) about this, and links to the API documentation for the `field` module.

since you are probably using a litlle-endian CPU, the chunk with `[0b…00, 0b0110…]` is being loaded with the second byte in high significance (0x32, 1x16, 1x8, 0x4) and the first byte in low significance (0x2, 0x1), because on little-endian CPUs the `.load()` method forwards to `.load_le()`

it's a complex module. i should probably deprecate the unsuffixed methods entirely, but they're nice to have for users who don't care about representation and exclusively interact through this trait.

you are interacting with memory through more than just the `BitField` trait, so you'll need to explicitly choose how you handle regions that inhabit multiple memory elements.

**Comment by dblclik** [comment]
Thank you very much for that explanation and help, @myrrlyn 🙏  I made two mistakes:  (1) I assumed loading in as `Msb0` was sufficient to ensure big-endian operations; and, (2) I was so curious about why it only _sometimes_ resulted in the unexpected value that I did not look into the other methods 🤦 

I have that chapter open now and look forward to reading it and the rest of the book (so far the docs.rs and the code have been plenty, but I am excited to read more).

I'm very much looking forward to finding more things to do with bitvec, it has been great to use thus far 🙌

**Comment by dblclik** [comment]
I closed the issue, but if you have any more information that would be helpful, please don't hesitate to share!
